name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different (e.g., `master`)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          echo "Building the project..."
          # Add any build commands here if needed, like npm install or other build tools

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tishandnayu # Specify the directory where your HTML files are located
